// ─── tugQuestions.ts ──────────────────────────────────────────────────────────
// Nigeria Primary 3 Curriculum questions for Tug of War
// 50+ questions per class level, covering all subjects

export interface TugQuestion {
  id: number;
  subject: string;
  topic: string;
  question: string;
  answer: string;        // numeric string or short text
  level: 'P1' | 'P2' | 'P3' | 'P4' | 'P5' | 'P6';
}

// ─── PRIMARY 1 ────────────────────────────────────────────────────────────────
const P1: TugQuestion[] = [
  // Mathematics
  { id:101, subject:'Maths', topic:'Addition', question:'2 + 3 = ?', answer:'5', level:'P1' },
  { id:102, subject:'Maths', topic:'Addition', question:'4 + 5 = ?', answer:'9', level:'P1' },
  { id:103, subject:'Maths', topic:'Addition', question:'6 + 3 = ?', answer:'9', level:'P1' },
  { id:104, subject:'Maths', topic:'Addition', question:'7 + 2 = ?', answer:'9', level:'P1' },
  { id:105, subject:'Maths', topic:'Addition', question:'5 + 5 = ?', answer:'10', level:'P1' },
  { id:106, subject:'Maths', topic:'Addition', question:'3 + 8 = ?', answer:'11', level:'P1' },
  { id:107, subject:'Maths', topic:'Addition', question:'6 + 6 = ?', answer:'12', level:'P1' },
  { id:108, subject:'Maths', topic:'Subtraction', question:'9 - 4 = ?', answer:'5', level:'P1' },
  { id:109, subject:'Maths', topic:'Subtraction', question:'10 - 3 = ?', answer:'7', level:'P1' },
  { id:110, subject:'Maths', topic:'Subtraction', question:'8 - 5 = ?', answer:'3', level:'P1' },
  { id:111, subject:'Maths', topic:'Subtraction', question:'12 - 7 = ?', answer:'5', level:'P1' },
  { id:112, subject:'Maths', topic:'Subtraction', question:'15 - 8 = ?', answer:'7', level:'P1' },
  { id:113, subject:'Maths', topic:'Numbers', question:'What comes after 19?', answer:'20', level:'P1' },
  { id:114, subject:'Maths', topic:'Numbers', question:'How many days in a week?', answer:'7', level:'P1' },
  { id:115, subject:'Maths', topic:'Numbers', question:'How many months in a year?', answer:'12', level:'P1' },
  { id:116, subject:'Maths', topic:'Shapes', question:'How many sides does a triangle have?', answer:'3', level:'P1' },
  { id:117, subject:'Maths', topic:'Shapes', question:'How many sides does a square have?', answer:'4', level:'P1' },
  { id:118, subject:'Maths', topic:'Numbers', question:'Double 5 = ?', answer:'10', level:'P1' },
  { id:119, subject:'Maths', topic:'Numbers', question:'Half of 10 = ?', answer:'5', level:'P1' },
  { id:120, subject:'Maths', topic:'Addition', question:'8 + 4 = ?', answer:'12', level:'P1' },
  // Quantitative Reasoning
  { id:121, subject:'Quantitative', topic:'Patterns', question:'2, 4, 6, ?, 10 — what is the missing number?', answer:'8', level:'P1' },
  { id:122, subject:'Quantitative', topic:'Patterns', question:'1, 3, 5, ?, 9 — what is the missing number?', answer:'7', level:'P1' },
  { id:123, subject:'Quantitative', topic:'Patterns', question:'5, 10, 15, ? — what comes next?', answer:'20', level:'P1' },
  { id:124, subject:'Quantitative', topic:'Comparison', question:'Which is greater: 9 or 6?', answer:'9', level:'P1' },
  { id:125, subject:'Quantitative', topic:'Comparison', question:'Which is less: 4 or 7?', answer:'4', level:'P1' },
  // English
  { id:126, subject:'English', topic:'Alphabet', question:'How many letters are in the English alphabet?', answer:'26', level:'P1' },
  { id:127, subject:'English', topic:'Vowels', question:'How many vowels are there?', answer:'5', level:'P1' },
  { id:128, subject:'English', topic:'Spelling', question:'Spell: a young cat (3 letters)', answer:'cat', level:'P1' },
  { id:129, subject:'English', topic:'Spelling', question:'Spell: a young dog (3 letters)', answer:'dog', level:'P1' },
  { id:130, subject:'English', topic:'Numbers', question:'How do you write "two" in figures?', answer:'2', level:'P1' },
  // General Knowledge
  { id:131, subject:'General', topic:'Nigeria', question:'Nigeria got independence in which year?', answer:'1960', level:'P1' },
  { id:132, subject:'General', topic:'Days', question:'How many days in a week?', answer:'7', level:'P1' },
  { id:133, subject:'General', topic:'Body', question:'How many legs does a human have?', answer:'2', level:'P1' },
  { id:134, subject:'General', topic:'Animals', question:'How many legs does a dog have?', answer:'4', level:'P1' },
  { id:135, subject:'General', topic:'Colours', question:'How many colours are in a rainbow?', answer:'7', level:'P1' },
  // More Maths
  { id:136, subject:'Maths', topic:'Addition', question:'9 + 9 = ?', answer:'18', level:'P1' },
  { id:137, subject:'Maths', topic:'Addition', question:'7 + 8 = ?', answer:'15', level:'P1' },
  { id:138, subject:'Maths', topic:'Subtraction', question:'20 - 7 = ?', answer:'13', level:'P1' },
  { id:139, subject:'Maths', topic:'Subtraction', question:'18 - 9 = ?', answer:'9', level:'P1' },
  { id:140, subject:'Maths', topic:'Numbers', question:'What is 10 + 10?', answer:'20', level:'P1' },
  { id:141, subject:'Maths', topic:'Money', question:'How many kobo make 1 Naira?', answer:'100', level:'P1' },
  { id:142, subject:'Maths', topic:'Time', question:'How many hours in a day?', answer:'24', level:'P1' },
  { id:143, subject:'Maths', topic:'Time', question:'How many minutes in an hour?', answer:'60', level:'P1' },
  { id:144, subject:'Maths', topic:'Time', question:'How many seconds in a minute?', answer:'60', level:'P1' },
  { id:145, subject:'Quantitative', topic:'Patterns', question:'10, 20, 30, ? — what comes next?', answer:'40', level:'P1' },
  { id:146, subject:'Maths', topic:'Addition', question:'14 + 6 = ?', answer:'20', level:'P1' },
  { id:147, subject:'Maths', topic:'Subtraction', question:'17 - 8 = ?', answer:'9', level:'P1' },
  { id:148, subject:'Maths', topic:'Numbers', question:'What is the value of 0 + 15?', answer:'15', level:'P1' },
  { id:149, subject:'Quantitative', topic:'Odd/Even', question:'Is 8 an even number? Type yes or no', answer:'yes', level:'P1' },
  { id:150, subject:'Quantitative', topic:'Odd/Even', question:'Is 7 an odd number? Type yes or no', answer:'yes', level:'P1' },
];

// ─── PRIMARY 2 ────────────────────────────────────────────────────────────────
const P2: TugQuestion[] = [
  { id:201, subject:'Maths', topic:'Multiplication', question:'3 × 4 = ?', answer:'12', level:'P2' },
  { id:202, subject:'Maths', topic:'Multiplication', question:'5 × 5 = ?', answer:'25', level:'P2' },
  { id:203, subject:'Maths', topic:'Multiplication', question:'2 × 9 = ?', answer:'18', level:'P2' },
  { id:204, subject:'Maths', topic:'Multiplication', question:'6 × 4 = ?', answer:'24', level:'P2' },
  { id:205, subject:'Maths', topic:'Multiplication', question:'7 × 3 = ?', answer:'21', level:'P2' },
  { id:206, subject:'Maths', topic:'Division', question:'20 ÷ 4 = ?', answer:'5', level:'P2' },
  { id:207, subject:'Maths', topic:'Division', question:'30 ÷ 5 = ?', answer:'6', level:'P2' },
  { id:208, subject:'Maths', topic:'Division', question:'18 ÷ 3 = ?', answer:'6', level:'P2' },
  { id:209, subject:'Maths', topic:'Addition', question:'45 + 36 = ?', answer:'81', level:'P2' },
  { id:210, subject:'Maths', topic:'Subtraction', question:'73 - 28 = ?', answer:'45', level:'P2' },
  { id:211, subject:'Maths', topic:'Place Value', question:'What is the tens digit in 374?', answer:'7', level:'P2' },
  { id:212, subject:'Maths', topic:'Place Value', question:'What is the hundreds digit in 628?', answer:'6', level:'P2' },
  { id:213, subject:'Maths', topic:'Fractions', question:'Half of 20 = ?', answer:'10', level:'P2' },
  { id:214, subject:'Maths', topic:'Fractions', question:'Quarter of 16 = ?', answer:'4', level:'P2' },
  { id:215, subject:'Maths', topic:'Fractions', question:'Half of 50 = ?', answer:'25', level:'P2' },
  { id:216, subject:'Maths', topic:'Money', question:'₦50 + ₦30 = ?', answer:'80', level:'P2' },
  { id:217, subject:'Maths', topic:'Money', question:'₦100 - ₦45 = ?', answer:'55', level:'P2' },
  { id:218, subject:'Maths', topic:'Shapes', question:'How many sides does a rectangle have?', answer:'4', level:'P2' },
  { id:219, subject:'Maths', topic:'Shapes', question:'How many sides does a pentagon have?', answer:'5', level:'P2' },
  { id:220, subject:'Maths', topic:'Measurement', question:'How many cm in 1 metre?', answer:'100', level:'P2' },
  { id:221, subject:'Quantitative', topic:'Patterns', question:'3, 6, 9, 12, ? — what comes next?', answer:'15', level:'P2' },
  { id:222, subject:'Quantitative', topic:'Patterns', question:'4, 8, 12, 16, ? — what comes next?', answer:'20', level:'P2' },
  { id:223, subject:'Quantitative', topic:'Patterns', question:'50, 45, 40, 35, ? — what comes next?', answer:'30', level:'P2' },
  { id:224, subject:'Quantitative', topic:'Number Series', question:'What is 2 more than 48?', answer:'50', level:'P2' },
  { id:225, subject:'Quantitative', topic:'Number Series', question:'What is 5 less than 30?', answer:'25', level:'P2' },
  { id:226, subject:'English', topic:'Grammar', question:'How many consonants are there in the English alphabet?', answer:'21', level:'P2' },
  { id:227, subject:'English', topic:'Spelling', question:'Spell the number after nineteen (one word)', answer:'twenty', level:'P2' },
  { id:228, subject:'English', topic:'Days', question:'How many letters in the word "SCHOOL"?', answer:'6', level:'P2' },
  { id:229, subject:'Science', topic:'Plants', question:'How many legs does an insect have?', answer:'6', level:'P2' },
  { id:230, subject:'Science', topic:'Animals', question:'How many legs does a spider have?', answer:'8', level:'P2' },
  { id:231, subject:'Maths', topic:'Multiplication', question:'8 × 5 = ?', answer:'40', level:'P2' },
  { id:232, subject:'Maths', topic:'Multiplication', question:'9 × 4 = ?', answer:'36', level:'P2' },
  { id:233, subject:'Maths', topic:'Multiplication', question:'6 × 6 = ?', answer:'36', level:'P2' },
  { id:234, subject:'Maths', topic:'Division', question:'24 ÷ 4 = ?', answer:'6', level:'P2' },
  { id:235, subject:'Maths', topic:'Division', question:'45 ÷ 9 = ?', answer:'5', level:'P2' },
  { id:236, subject:'Maths', topic:'Addition', question:'63 + 27 = ?', answer:'90', level:'P2' },
  { id:237, subject:'Maths', topic:'Subtraction', question:'90 - 35 = ?', answer:'55', level:'P2' },
  { id:238, subject:'Maths', topic:'Fractions', question:'1/4 of 40 = ?', answer:'10', level:'P2' },
  { id:239, subject:'Maths', topic:'Measurement', question:'1 km = how many metres?', answer:'1000', level:'P2' },
  { id:240, subject:'Maths', topic:'Time', question:'15 minutes = how many seconds?', answer:'900', level:'P2' },
  { id:241, subject:'Quantitative', topic:'Analogy', question:'2 is to 4 as 5 is to ?', answer:'10', level:'P2' },
  { id:242, subject:'Quantitative', topic:'Analogy', question:'3 is to 9 as 4 is to ?', answer:'12', level:'P2' },
  { id:243, subject:'Maths', topic:'Money', question:'₦200 - ₦75 = ?', answer:'125', level:'P2' },
  { id:244, subject:'Maths', topic:'Money', question:'₦150 + ₦85 = ?', answer:'235', level:'P2' },
  { id:245, subject:'Science', topic:'Body', question:'How many bones are in the human body?', answer:'206', level:'P2' },
  { id:246, subject:'Maths', topic:'Multiplication', question:'10 × 10 = ?', answer:'100', level:'P2' },
  { id:247, subject:'Maths', topic:'Multiplication', question:'7 × 8 = ?', answer:'56', level:'P2' },
  { id:248, subject:'Maths', topic:'Place Value', question:'In 845, what is the ones digit?', answer:'5', level:'P2' },
  { id:249, subject:'Quantitative', topic:'Missing Number', question:'? + 14 = 30', answer:'16', level:'P2' },
  { id:250, subject:'Quantitative', topic:'Missing Number', question:'36 - ? = 20', answer:'16', level:'P2' },
];

// ─── PRIMARY 3 ────────────────────────────────────────────────────────────────
const P3: TugQuestion[] = [
  { id:301, subject:'Maths', topic:'Multiplication', question:'7 × 8 = ?', answer:'56', level:'P3' },
  { id:302, subject:'Maths', topic:'Multiplication', question:'9 × 6 = ?', answer:'54', level:'P3' },
  { id:303, subject:'Maths', topic:'Multiplication', question:'8 × 8 = ?', answer:'64', level:'P3' },
  { id:304, subject:'Maths', topic:'Multiplication', question:'12 × 4 = ?', answer:'48', level:'P3' },
  { id:305, subject:'Maths', topic:'Division', question:'56 ÷ 7 = ?', answer:'8', level:'P3' },
  { id:306, subject:'Maths', topic:'Division', question:'72 ÷ 9 = ?', answer:'8', level:'P3' },
  { id:307, subject:'Maths', topic:'Division', question:'48 ÷ 6 = ?', answer:'8', level:'P3' },
  { id:308, subject:'Maths', topic:'Fractions', question:'1/4 of 60 = ?', answer:'15', level:'P3' },
  { id:309, subject:'Maths', topic:'Fractions', question:'3/4 of 40 = ?', answer:'30', level:'P3' },
  { id:310, subject:'Maths', topic:'Fractions', question:'1/3 of 90 = ?', answer:'30', level:'P3' },
  { id:311, subject:'Maths', topic:'Money', question:'₦500 - ₦375 = ? (in Naira)', answer:'125', level:'P3' },
  { id:312, subject:'Maths', topic:'Money', question:'₦150 + ₦245 = ? (in Naira)', answer:'395', level:'P3' },
  { id:313, subject:'Maths', topic:'Perimeter', question:'Perimeter of square with side 7 cm = ? cm', answer:'28', level:'P3' },
  { id:314, subject:'Maths', topic:'Perimeter', question:'Perimeter of rectangle 8 cm × 5 cm = ? cm', answer:'26', level:'P3' },
  { id:315, subject:'Maths', topic:'Measurement', question:'3 metres = ? cm', answer:'300', level:'P3' },
  { id:316, subject:'Maths', topic:'Measurement', question:'5 kg = ? grams', answer:'5000', level:'P3' },
  { id:317, subject:'Maths', topic:'Place Value', question:'Value of 5 in 3,542 = ?', answer:'500', level:'P3' },
  { id:318, subject:'Maths', topic:'Place Value', question:'In 7,836 — what is the thousands digit?', answer:'7', level:'P3' },
  { id:319, subject:'Maths', topic:'Addition', question:'456 + 237 = ?', answer:'693', level:'P3' },
  { id:320, subject:'Maths', topic:'Subtraction', question:'800 - 367 = ?', answer:'433', level:'P3' },
  { id:321, subject:'Quantitative', topic:'Patterns', question:'7, 14, 21, 28, ? — next?', answer:'35', level:'P3' },
  { id:322, subject:'Quantitative', topic:'Patterns', question:'100, 90, 80, 70, ? — next?', answer:'60', level:'P3' },
  { id:323, subject:'Quantitative', topic:'Analogy', question:'6 is to 36 as 7 is to ?', answer:'49', level:'P3' },
  { id:324, subject:'Quantitative', topic:'Analogy', question:'3 is to 27 as 4 is to ?', answer:'64', level:'P3' },
  { id:325, subject:'Quantitative', topic:'Missing Number', question:'? × 8 = 64', answer:'8', level:'P3' },
  { id:326, subject:'Quantitative', topic:'Missing Number', question:'? ÷ 6 = 9', answer:'54', level:'P3' },
  { id:327, subject:'Quantitative', topic:'Missing Number', question:'45 + ? = 100', answer:'55', level:'P3' },
  { id:328, subject:'Quantitative', topic:'Odd/Even', question:'What is the next even number after 48?', answer:'50', level:'P3' },
  { id:329, subject:'Quantitative', topic:'Odd/Even', question:'What is the next odd number after 33?', answer:'35', level:'P3' },
  { id:330, subject:'Quantitative', topic:'Number Series', question:'25, 50, 75, ? — next?', answer:'100', level:'P3' },
  { id:331, subject:'English', topic:'Grammar', question:'How many letters in "NIGERIA"?', answer:'7', level:'P3' },
  { id:332, subject:'English', topic:'Grammar', question:'Plural of "child" — how many letters?', answer:'8', level:'P3' },
  { id:333, subject:'Science', topic:'Plants', question:'How many legs does an ant have?', answer:'6', level:'P3' },
  { id:334, subject:'Science', topic:'Human Body', question:'Normal human body temperature in °C = ?', answer:'37', level:'P3' },
  { id:335, subject:'Science', topic:'Human Body', question:'How many teeth does an adult have?', answer:'32', level:'P3' },
  { id:336, subject:'Social', topic:'Nigeria', question:'Nigeria has how many states?', answer:'36', level:'P3' },
  { id:337, subject:'Social', topic:'Nigeria', question:'In what year did Nigeria gain independence?', answer:'1960', level:'P3' },
  { id:338, subject:'Maths', topic:'Multiplication', question:'11 × 6 = ?', answer:'66', level:'P3' },
  { id:339, subject:'Maths', topic:'Multiplication', question:'9 × 9 = ?', answer:'81', level:'P3' },
  { id:340, subject:'Maths', topic:'Division', question:'100 ÷ 4 = ?', answer:'25', level:'P3' },
  { id:341, subject:'Maths', topic:'Fractions', question:'2/5 of 50 = ?', answer:'20', level:'P3' },
  { id:342, subject:'Maths', topic:'Fractions', question:'1/2 of 84 = ?', answer:'42', level:'P3' },
  { id:343, subject:'Maths', topic:'Time', question:'How many minutes in 2 hours?', answer:'120', level:'P3' },
  { id:344, subject:'Maths', topic:'Time', question:'Market opens 8am, closes 5pm. Hours open = ?', answer:'9', level:'P3' },
  { id:345, subject:'Quantitative', topic:'Analogy', question:'2 is to 8 as 3 is to ?', answer:'27', level:'P3' },
  { id:346, subject:'Quantitative', topic:'Missing Number', question:'72 ÷ ? = 8', answer:'9', level:'P3' },
  { id:347, subject:'Maths', topic:'Shapes', question:'How many sides does a hexagon have?', answer:'6', level:'P3' },
  { id:348, subject:'Maths', topic:'Shapes', question:'How many sides does an octagon have?', answer:'8', level:'P3' },
  { id:349, subject:'Maths', topic:'Perimeter', question:'Square with perimeter 36 cm — side = ? cm', answer:'9', level:'P3' },
  { id:350, subject:'Quantitative', topic:'Patterns', question:'2, 4, 8, 16, ? — next?', answer:'32', level:'P3' },
];

// ─── PRIMARY 4 ────────────────────────────────────────────────────────────────
const P4: TugQuestion[] = [
  { id:401, subject:'Maths', topic:'Multiplication', question:'23 × 4 = ?', answer:'92', level:'P4' },
  { id:402, subject:'Maths', topic:'Multiplication', question:'15 × 6 = ?', answer:'90', level:'P4' },
  { id:403, subject:'Maths', topic:'Multiplication', question:'18 × 5 = ?', answer:'90', level:'P4' },
  { id:404, subject:'Maths', topic:'Division', question:'144 ÷ 12 = ?', answer:'12', level:'P4' },
  { id:405, subject:'Maths', topic:'Division', question:'132 ÷ 11 = ?', answer:'12', level:'P4' },
  { id:406, subject:'Maths', topic:'Fractions', question:'3/8 of 64 = ?', answer:'24', level:'P4' },
  { id:407, subject:'Maths', topic:'Fractions', question:'5/6 of 60 = ?', answer:'50', level:'P4' },
  { id:408, subject:'Maths', topic:'Fractions', question:'2/3 of 48 = ?', answer:'32', level:'P4' },
  { id:409, subject:'Maths', topic:'Decimals', question:'0.5 × 10 = ?', answer:'5', level:'P4' },
  { id:410, subject:'Maths', topic:'Decimals', question:'1.5 + 2.5 = ?', answer:'4', level:'P4' },
  { id:411, subject:'Maths', topic:'Area', question:'Area of rectangle 6 cm × 8 cm = ? cm²', answer:'48', level:'P4' },
  { id:412, subject:'Maths', topic:'Area', question:'Area of square with side 9 cm = ? cm²', answer:'81', level:'P4' },
  { id:413, subject:'Maths', topic:'Perimeter', question:'Rectangle 12 cm × 5 cm — perimeter = ? cm', answer:'34', level:'P4' },
  { id:414, subject:'Maths', topic:'Money', question:'₦1,200 + ₦850 = ?', answer:'2050', level:'P4' },
  { id:415, subject:'Maths', topic:'Money', question:'₦5,000 - ₦2,750 = ?', answer:'2250', level:'P4' },
  { id:416, subject:'Maths', topic:'Addition', question:'1,345 + 2,678 = ?', answer:'4023', level:'P4' },
  { id:417, subject:'Maths', topic:'Subtraction', question:'5,000 - 1,786 = ?', answer:'3214', level:'P4' },
  { id:418, subject:'Maths', topic:'Place Value', question:'Value of 4 in 24,567 = ?', answer:'4000', level:'P4' },
  { id:419, subject:'Maths', topic:'Measurement', question:'2.5 km = ? metres', answer:'2500', level:'P4' },
  { id:420, subject:'Maths', topic:'Measurement', question:'3,500 g = ? kg', answer:'3.5', level:'P4' },
  { id:421, subject:'Quantitative', topic:'Patterns', question:'1, 4, 9, 16, ? — next (square numbers)?', answer:'25', level:'P4' },
  { id:422, subject:'Quantitative', topic:'Patterns', question:'1, 1, 2, 3, 5, ? — next (Fibonacci)?', answer:'8', level:'P4' },
  { id:423, subject:'Quantitative', topic:'Analogy', question:'144 ÷ 12 = ? × 3', answer:'4', level:'P4' },
  { id:424, subject:'Quantitative', topic:'Missing Number', question:'? % of 200 = 50', answer:'25', level:'P4' },
  { id:425, subject:'Quantitative', topic:'Missing Number', question:'√64 = ?', answer:'8', level:'P4' },
  { id:426, subject:'Science', topic:'Physics', question:'Sound travels fastest through which medium: solid, liquid, or gas? (1 word)', answer:'solid', level:'P4' },
  { id:427, subject:'Science', topic:'Chemistry', question:'Water boils at ? °C', answer:'100', level:'P4' },
  { id:428, subject:'Science', topic:'Chemistry', question:'Water freezes at ? °C', answer:'0', level:'P4' },
  { id:429, subject:'Social', topic:'Nigeria', question:'FCT Abuja became Nigeria\'s capital in which year?', answer:'1991', level:'P4' },
  { id:430, subject:'Social', topic:'Nigeria', question:'Nigeria has how many geopolitical zones?', answer:'6', level:'P4' },
  { id:431, subject:'Maths', topic:'Multiplication', question:'25 × 8 = ?', answer:'200', level:'P4' },
  { id:432, subject:'Maths', topic:'Multiplication', question:'32 × 5 = ?', answer:'160', level:'P4' },
  { id:433, subject:'Maths', topic:'Division', question:'180 ÷ 9 = ?', answer:'20', level:'P4' },
  { id:434, subject:'Maths', topic:'Fractions', question:'Add 1/4 + 1/4 = ?', answer:'1/2', level:'P4' },
  { id:435, subject:'Maths', topic:'Fractions', question:'Subtract 3/5 - 1/5 = ?', answer:'2/5', level:'P4' },
  { id:436, subject:'Maths', topic:'Decimals', question:'3.7 + 1.8 = ?', answer:'5.5', level:'P4' },
  { id:437, subject:'Maths', topic:'Decimals', question:'5.0 - 2.4 = ?', answer:'2.6', level:'P4' },
  { id:438, subject:'Maths', topic:'Area', question:'Triangle base 10 cm, height 6 cm — area = ? cm²', answer:'30', level:'P4' },
  { id:439, subject:'Quantitative', topic:'LCM', question:'LCM of 4 and 6 = ?', answer:'12', level:'P4' },
  { id:440, subject:'Quantitative', topic:'HCF', question:'HCF of 12 and 18 = ?', answer:'6', level:'P4' },
  { id:441, subject:'Quantitative', topic:'Prime', question:'Is 13 a prime number? yes or no', answer:'yes', level:'P4' },
  { id:442, subject:'Quantitative', topic:'Prime', question:'What is the smallest prime number?', answer:'2', level:'P4' },
  { id:443, subject:'Maths', topic:'Ratio', question:'Ratio 3:6 simplified = 1:?', answer:'2', level:'P4' },
  { id:444, subject:'Maths', topic:'Percentage', question:'50% of 80 = ?', answer:'40', level:'P4' },
  { id:445, subject:'Maths', topic:'Percentage', question:'25% of 120 = ?', answer:'30', level:'P4' },
  { id:446, subject:'Maths', topic:'Time', question:'3 hours 45 min + 1 hour 30 min = ? hours ? min (just the minutes part)', answer:'15', level:'P4' },
  { id:447, subject:'Science', topic:'Plants', question:'How many chambers does the human heart have?', answer:'4', level:'P4' },
  { id:448, subject:'Maths', topic:'Multiplication', question:'14 × 7 = ?', answer:'98', level:'P4' },
  { id:449, subject:'Maths', topic:'Division', question:'156 ÷ 12 = ?', answer:'13', level:'P4' },
  { id:450, subject:'Quantitative', topic:'Missing Number', question:'3² + 4² = ?', answer:'25', level:'P4' },
];

// ─── PRIMARY 5 ────────────────────────────────────────────────────────────────
const P5: TugQuestion[] = [
  { id:501, subject:'Maths', topic:'Percentages', question:'30% of 250 = ?', answer:'75', level:'P5' },
  { id:502, subject:'Maths', topic:'Percentages', question:'15% of 200 = ?', answer:'30', level:'P5' },
  { id:503, subject:'Maths', topic:'Percentages', question:'What % of 50 is 10?', answer:'20', level:'P5' },
  { id:504, subject:'Maths', topic:'Fractions', question:'2/3 + 1/6 = ? (give answer as fraction)', answer:'5/6', level:'P5' },
  { id:505, subject:'Maths', topic:'Fractions', question:'3/4 - 1/8 = ?', answer:'5/8', level:'P5' },
  { id:506, subject:'Maths', topic:'Fractions', question:'2/3 × 3/4 = ?', answer:'1/2', level:'P5' },
  { id:507, subject:'Maths', topic:'Decimals', question:'12.5 × 4 = ?', answer:'50', level:'P5' },
  { id:508, subject:'Maths', topic:'Decimals', question:'8.4 ÷ 2 = ?', answer:'4.2', level:'P5' },
  { id:509, subject:'Maths', topic:'Ratio', question:'In ratio 3:5, if first part = 9, second part = ?', answer:'15', level:'P5' },
  { id:510, subject:'Maths', topic:'Ratio', question:'Divide 40 in ratio 3:5 — smaller share = ?', answer:'15', level:'P5' },
  { id:511, subject:'Maths', topic:'Area', question:'Circle radius 7 cm — circumference ≈ ? cm (use π=22/7)', answer:'44', level:'P5' },
  { id:512, subject:'Maths', topic:'Area', question:'Area of circle r=7 cm ≈ ? cm² (π=22/7)', answer:'154', level:'P5' },
  { id:513, subject:'Maths', topic:'Volume', question:'Volume of cuboid 4×3×5 cm³ = ?', answer:'60', level:'P5' },
  { id:514, subject:'Maths', topic:'Volume', question:'Volume of cube with side 4 cm = ? cm³', answer:'64', level:'P5' },
  { id:515, subject:'Maths', topic:'Algebra', question:'If x + 7 = 15, then x = ?', answer:'8', level:'P5' },
  { id:516, subject:'Maths', topic:'Algebra', question:'If 3y = 24, then y = ?', answer:'8', level:'P5' },
  { id:517, subject:'Maths', topic:'Algebra', question:'If 2a - 3 = 11, then a = ?', answer:'7', level:'P5' },
  { id:518, subject:'Maths', topic:'Statistics', question:'Mean of 4, 6, 8, 10 = ?', answer:'7', level:'P5' },
  { id:519, subject:'Maths', topic:'Statistics', question:'Mean of 5, 10, 15 = ?', answer:'10', level:'P5' },
  { id:520, subject:'Maths', topic:'Statistics', question:'Median of 3, 7, 9, 11, 15 = ?', answer:'9', level:'P5' },
  { id:521, subject:'Quantitative', topic:'Patterns', question:'1, 8, 27, 64, ? — next (cube numbers)?', answer:'125', level:'P5' },
  { id:522, subject:'Quantitative', topic:'Prime Factors', question:'Prime factors of 12 — how many prime factors?', answer:'2', level:'P5' },
  { id:523, subject:'Quantitative', topic:'LCM', question:'LCM of 6, 8, and 12 = ?', answer:'24', level:'P5' },
  { id:524, subject:'Quantitative', topic:'HCF', question:'HCF of 24, 36, and 48 = ?', answer:'12', level:'P5' },
  { id:525, subject:'Quantitative', topic:'Probability', question:'P(head) when tossing a coin = ? (as fraction)', answer:'1/2', level:'P5' },
  { id:526, subject:'Science', topic:'Physics', question:'Speed = Distance ÷ Time. Distance 60km, Time 2hrs. Speed = ? km/h', answer:'30', level:'P5' },
  { id:527, subject:'Science', topic:'Chemistry', question:'How many elements are in H₂O?', answer:'2', level:'P5' },
  { id:528, subject:'Science', topic:'Biology', question:'Photosynthesis equation: plants use sunlight + water + ? to make food', answer:'co2', level:'P5' },
  { id:529, subject:'Social', topic:'Geography', question:'What is the longest river in Nigeria?', answer:'niger', level:'P5' },
  { id:530, subject:'Social', topic:'Nigeria', question:'Nigeria is in which continent?', answer:'africa', level:'P5' },
  { id:531, subject:'Maths', topic:'Percentages', question:'A shirt costs ₦800. 10% discount = new price in ₦?', answer:'720', level:'P5' },
  { id:532, subject:'Maths', topic:'Percentages', question:'Score 36 out of 40. Percentage = ?', answer:'90', level:'P5' },
  { id:533, subject:'Maths', topic:'Fractions', question:'1 and 1/2 + 2 and 1/4 = ? (as decimal)', answer:'3.75', level:'P5' },
  { id:534, subject:'Maths', topic:'Algebra', question:'5x = 45, x = ?', answer:'9', level:'P5' },
  { id:535, subject:'Maths', topic:'Algebra', question:'x/4 = 7, x = ?', answer:'28', level:'P5' },
  { id:536, subject:'Maths', topic:'Statistics', question:'Mode of: 3, 5, 5, 7, 9, 5 = ?', answer:'5', level:'P5' },
  { id:537, subject:'Maths', topic:'Area', question:'Perimeter of circle r=14 cm (π=22/7) = ? cm', answer:'88', level:'P5' },
  { id:538, subject:'Quantitative', topic:'Missing Number', question:'√144 = ?', answer:'12', level:'P5' },
  { id:539, subject:'Quantitative', topic:'Missing Number', question:'√225 = ?', answer:'15', level:'P5' },
  { id:540, subject:'Quantitative', topic:'Number Series', question:'2, 6, 18, 54, ? (multiply by 3)', answer:'162', level:'P5' },
  { id:541, subject:'Maths', topic:'Ratio', question:'Ratio 4:6:8 simplified — smallest number = ?', answer:'2', level:'P5' },
  { id:542, subject:'Maths', topic:'Volume', question:'Cube volume = 125 cm³. Side = ? cm', answer:'5', level:'P5' },
  { id:543, subject:'Maths', topic:'Angles', question:'Angles in a triangle add up to ? degrees', answer:'180', level:'P5' },
  { id:544, subject:'Maths', topic:'Angles', question:'A right angle = ? degrees', answer:'90', level:'P5' },
  { id:545, subject:'Maths', topic:'Angles', question:'Angles in a quadrilateral add up to ? degrees', answer:'360', level:'P5' },
  { id:546, subject:'Science', topic:'Physics', question:'Force = Mass × Acceleration. Mass=5kg, Accel=3m/s². Force = ? N', answer:'15', level:'P5' },
  { id:547, subject:'Maths', topic:'Decimals', question:'0.25 × 40 = ?', answer:'10', level:'P5' },
  { id:548, subject:'Maths', topic:'Decimals', question:'3.6 ÷ 0.4 = ?', answer:'9', level:'P5' },
  { id:549, subject:'Quantitative', topic:'Proportion', question:'If 4 books cost ₦200, how much do 10 books cost?', answer:'500', level:'P5' },
  { id:550, subject:'Quantitative', topic:'Proportion', question:'If 6 workers finish in 4 days, how many days for 8 workers?', answer:'3', level:'P5' },
];

// ─── PRIMARY 6 ────────────────────────────────────────────────────────────────
const P6: TugQuestion[] = [
  { id:601, subject:'Maths', topic:'Algebra', question:'Expand: 3(x + 4) when x=2 = ?', answer:'18', level:'P6' },
  { id:602, subject:'Maths', topic:'Algebra', question:'Solve: 2x + 5 = 17. x = ?', answer:'6', level:'P6' },
  { id:603, subject:'Maths', topic:'Algebra', question:'Solve: 4x - 8 = 20. x = ?', answer:'7', level:'P6' },
  { id:604, subject:'Maths', topic:'Statistics', question:'Range of: 4, 9, 2, 15, 7 = ?', answer:'13', level:'P6' },
  { id:605, subject:'Maths', topic:'Statistics', question:'Mean of: 12, 8, 16, 10, 14 = ?', answer:'12', level:'P6' },
  { id:606, subject:'Maths', topic:'Percentages', question:'Profit of ₦200 on cost of ₦1000 = ? % profit', answer:'20', level:'P6' },
  { id:607, subject:'Maths', topic:'Percentages', question:'Loss of ₦150 on cost of ₦600 = ? % loss', answer:'25', level:'P6' },
  { id:608, subject:'Maths', topic:'Interest', question:'Simple interest on ₦5000 at 10% for 2 years = ₦?', answer:'1000', level:'P6' },
  { id:609, subject:'Maths', topic:'Interest', question:'SI = PRT/100. P=₦8000, R=5%, T=3yrs. SI = ₦?', answer:'1200', level:'P6' },
  { id:610, subject:'Maths', topic:'Area', question:'Area of trapezium with parallel sides 6&10, height 4 = ? cm²', answer:'32', level:'P6' },
  { id:611, subject:'Maths', topic:'Angles', question:'Exterior angle of a regular hexagon = ? degrees', answer:'60', level:'P6' },
  { id:612, subject:'Maths', topic:'Angles', question:'Interior angles of regular pentagon each = ? degrees', answer:'108', level:'P6' },
  { id:613, subject:'Maths', topic:'Graphs', question:'Slope of line from (0,0) to (4,8) = ?', answer:'2', level:'P6' },
  { id:614, subject:'Maths', topic:'Indices', question:'2³ × 2² = 2 to the power ? ', answer:'5', level:'P6' },
  { id:615, subject:'Maths', topic:'Indices', question:'3⁴ = ?', answer:'81', level:'P6' },
  { id:616, subject:'Maths', topic:'Fractions', question:'Divide 3/4 by 1/2 = ?', answer:'3/2', level:'P6' },
  { id:617, subject:'Maths', topic:'Fractions', question:'1 and 2/3 × 1 and 1/5 = ? (as fraction)', answer:'2', level:'P6' },
  { id:618, subject:'Maths', topic:'Ratio', question:'Divide ₦720 in ratio 3:5. Larger share = ₦?', answer:'450', level:'P6' },
  { id:619, subject:'Maths', topic:'Ratio', question:'Map scale 1:50000. 3 cm on map = ? km real', answer:'1.5', level:'P6' },
  { id:620, subject:'Maths', topic:'Volume', question:'Volume of cylinder r=7, h=10 ≈ ? cm³ (π=22/7)', answer:'1540', level:'P6' },
  { id:621, subject:'Quantitative', topic:'Number Bases', question:'1101 in base 2 = ? in base 10', answer:'13', level:'P6' },
  { id:622, subject:'Quantitative', topic:'Number Bases', question:'23 in base 10 = ? in base 2 (decimal result of: 10111₂)', answer:'23', level:'P6' },
  { id:623, subject:'Quantitative', topic:'Set Theory', question:'A={1,2,3}, B={2,3,4}. A∩B has how many elements?', answer:'2', level:'P6' },
  { id:624, subject:'Quantitative', topic:'Set Theory', question:'A={1,2,3}, B={2,3,4}. A∪B has how many elements?', answer:'4', level:'P6' },
  { id:625, subject:'Quantitative', topic:'Probability', question:'Die thrown. P(even number) = ? (as fraction)', answer:'1/2', level:'P6' },
  { id:626, subject:'Science', topic:'Physics', question:'Density = Mass/Volume. Mass=200g, Vol=40cm³. Density = ? g/cm³', answer:'5', level:'P6' },
  { id:627, subject:'Science', topic:'Chemistry', question:'How many protons does Carbon (C) have?', answer:'6', level:'P6' },
  { id:628, subject:'Science', topic:'Biology', question:'How many chromosomes does a human cell have?', answer:'46', level:'P6' },
  { id:629, subject:'Social', topic:'Economics', question:'Nigeria\'s currency is Naira. 1 Naira = ? kobo', answer:'100', level:'P6' },
  { id:630, subject:'Social', topic:'Government', question:'Nigeria has a Federal, State, and ? level of government (one word)', answer:'local', level:'P6' },
  { id:631, subject:'Maths', topic:'Algebra', question:'If 2x + 3y = 12 and x=3, then y = ?', answer:'2', level:'P6' },
  { id:632, subject:'Maths', topic:'Statistics', question:'Median of: 2, 5, 7, 10, 13, 17 = ?', answer:'8.5', level:'P6' },
  { id:633, subject:'Maths', topic:'Percentages', question:'₦2,500 increased by 20% = ₦?', answer:'3000', level:'P6' },
  { id:634, subject:'Maths', topic:'Percentages', question:'₦3,600 decreased by 25% = ₦?', answer:'2700', level:'P6' },
  { id:635, subject:'Maths', topic:'Interest', question:'Amount after SI: P=₦10000, R=8%, T=2yr. Total = ₦?', answer:'11600', level:'P6' },
  { id:636, subject:'Maths', topic:'Area', question:'Area of circle d=14cm (π=22/7) = ? cm²', answer:'154', level:'P6' },
  { id:637, subject:'Maths', topic:'Indices', question:'5⁰ = ?', answer:'1', level:'P6' },
  { id:638, subject:'Maths', topic:'Indices', question:'2⁻¹ = ? (as fraction)', answer:'1/2', level:'P6' },
  { id:639, subject:'Quantitative', topic:'Patterns', question:'3, 5, 8, 13, 21, ? (each = sum of 2 before)', answer:'34', level:'P6' },
  { id:640, subject:'Quantitative', topic:'Missing Operator', question:'6 ? 4 = 24 — what operator (×, ÷, +, -)?', answer:'×', level:'P6' },
  { id:641, subject:'Maths', topic:'Ratio', question:'If 5:8 = 25:?, then ? = ?', answer:'40', level:'P6' },
  { id:642, subject:'Maths', topic:'Algebra', question:'Simplify: 3a + 2b - a + 4b. Coefficient of b = ?', answer:'6', level:'P6' },
  { id:643, subject:'Maths', topic:'Volume', question:'Surface area of cube side 5cm = ? cm²', answer:'150', level:'P6' },
  { id:644, subject:'Quantitative', topic:'Probability', question:'Bag: 3 red, 5 blue. P(blue) = ? (as fraction)', answer:'5/8', level:'P6' },
  { id:645, subject:'Quantitative', topic:'Venn Diagram', question:'30 pupils; 18 like football, 15 like basketball, 8 like both. Like neither = ?', answer:'5', level:'P6' },
  { id:646, subject:'Science', topic:'Physics', question:'Work = Force × Distance. F=20N, D=5m. Work = ? joules', answer:'100', level:'P6' },
  { id:647, subject:'Maths', topic:'Angles', question:'Angles of a triangle: 60°, 80°. Third angle = ?°', answer:'40', level:'P6' },
  { id:648, subject:'Maths', topic:'Angles', question:'Corresponding angles: one = 72°. The other = ?°', answer:'72', level:'P6' },
  { id:649, subject:'Maths', topic:'Graphs', question:'y = 2x + 3. When x = 4, y = ?', answer:'11', level:'P6' },
  { id:650, subject:'Maths', topic:'Statistics', question:'Data: 3,3,5,7,7,7,9. Mode = ?', answer:'7', level:'P6' },
];

export const ALL_TUG_QUESTIONS: Record<string, TugQuestion[]> = {
  P1, P2, P3, P4, P5, P6,
};

export function getQuestionsForLevel(level: string, subject?: string): TugQuestion[] {
  const questions = ALL_TUG_QUESTIONS[level] || P3;
  if (!subject || subject === 'All') return questions;
  // Filter by subject (case-insensitive)
  return questions.filter(q => q.subject.toLowerCase() === subject.toLowerCase());
}

export function shuffleQuestions(arr: TugQuestion[]): TugQuestion[] {
  return [...arr].sort(() => Math.random() - 0.5);
}
